### ISSUE TITLE
Kodi ALSA configuration

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [flathub/tv.kodi.Kodi#87]
Where can I config Kodi to use ALSA?

**Comment by Marko10-000** [comment]
I'm not sure what you want to do. I recommend to use a PulseAudio-Server. ALSA is just a suitable option when you want to run it in standalone mode (witch isn't currently official support by the Kodi flatpak). Please check the [Kodi wiki](https://kodi.wiki/view/PulseAudio) if ALSA is really required (because this leads to a lot of trouble on my side. I'm using jack for a more complex audio processing/routing and it seams that I have to kill my jack server to test it). Besides you can run a quick tests with `pasuspender -- env AE_SINK=ALSA flatpak run tv.kodi.Kodi//stable` (Please be aware that Kodi get into a deadlock when it can't allocate the ALSA device after you want to exit the program. You have to kill it from the outside to close the Kodi window/terminate the Kodi process). I hope it helped you somehow and when sill ALSA support is required message us again.

**Comment by razzeee** [comment]
Closing due to missing feedback.
